---
abstract: 'A module for merging hierarchies using the C3 algorithm'
author:
  - 'Stevan Little <stevan@iinteractive.com>'
  - 'Brandon L. Black <blblack@gmail.com>'
build_requires:
  Test::More: '0.47'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Algorithm-C3
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0.01'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Algorithm-C3
  repository: git://git.shadowcat.co.uk/gitmo/Algorithm-C3.git
version: '0.09'
